control "V-38488" do
  title "The operating system must conduct backups of user-level information
contained in the operating system per organization defined frequency to conduct
backups consistent with recovery time and recovery point objectives."
  desc  "Operating system backup is a critical step in maintaining data
assurance and availability. User-level information is data generated by
information system and/or application users. Backups shall be consistent with
organizational recovery time and recovery point objectives."
  impact 'medium'
  tag "gtitle": "SRG-OS-000099"
  tag "gid": "V-38488"
  tag "rid": "SV-50289r1_rule"
  tag "stig_id": "RHEL-06-000504"
  tag "fix_id": "F-43435r1_fix"
  tag "cci": ["CCI-000535"]
  tag "nist": ["CP-9a", "Rev_4"]
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  desc 'check', "Ask an administrator if a process exists to back up user data
from the system.

If such a process does not exist, this is a finding."
  desc 'fix', "Procedures to back up user data from the system must be
established and executed. The Red Hat operating system provides utilities for
automating such a process.  Commercial and open-source products are also
available.

Implement a process whereby user data is backed up from the system in
accordance with local policies."

  describe "Manual test" do
    skip "This control must be reviewed manually"
  end
end

